# ~/.config/starship.toml

format = """$directory$git_branch$character"""

[hostname]
ssh_only = true
style = "bold dimmed"

[battery]
full_symbol = "ï‰€ "
charging_symbol = "ï‡¦ "
discharging_symbol = "ï‰‚ "
disabled = false

[git_branch]
symbol = "îœ¥ " 
style = "bold #fab387"

[git_status]
conflicted = "ğŸ³"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
style = "dimmed"

[nodejs]
symbol = "ï¢˜ "
style = "bold"

[package]
symbol = "ğŸ“¦ "
style = "bold"
